jwt:
  secretkey: assajfbcvsdyavbjsKbdwufibj32879et24677reyshbbjdsfv2876r236rt71v

server:
  webflux:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/orders/**
          filters:
            - StripPrefix=0
            - name : LoggingOrdersFilter
            -  name : Authentication
               args:
                 isEnabled: true
            - name : Authorization
              args:
                allowedRoles: ADMIN, SUPER_ADMIN

        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/inventory/**
          filters:
            - StripPrefix=0
            - name: Authentication


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
